# base image
FROM node:12.2.0-alpine

WORKDIR /app
COPY . ./
EXPOSE 3000
# install and cache app dependencies
RUN npm install
RUN npm build
RUN npm install -g serve

# start app
CMD ["serve", "-s", "build", "-l", "3000"]