version: '3'
services:
  web:
    image: markusjuopperi/dockerdemo:latest
    build:
      context: backend/
      dockerfile: Dockerfile
    depends_on:
      - "db"
    ports:
      - "8091:8080"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  frontend:
    image: markusjuopperi/frontend:latest
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development